apiVersion: v1
kind: ServiceAccount
metadata:
  name: progressivedaemonset
  namespace: progressivedaemonset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: progressivedaemonset
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets" ]
    verbs: [ "get", "list", "watch", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: progressivedaemonset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: progressivedaemonset
subjects:
  - kind: ServiceAccount
    name: progressivedaemonset
    namespace: progressivedaemonset
