apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: progressive-rollout-controller
  labels:
    app: webhook-service
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: webhook-server
  selector:
    app: gate-remover-controller
